### GET ALL CATEGORIES
Get http://localhost:8080/api/recipes
Accept: application/json


### CREATE NEW CATEGORY
POST http://localhost:8080/api/recipe
Accept: application/json
Content-Type: application/json

{
  "title": "Spaghetti Bolognese Fake",
  "description": "Delicious pasta",
  "image": "Gambar.com",
  "nutrition": {
    "calories": "400 kcal",
    "total_fat": "12g",
    "protein": "20g",
    "carbohydrate": "50g",
    "cholesterol": "0mg",
    "description": "Low sugar",
    "vitamin":"C"
  },
  "main_dish": ["pasta", "meat"],
  "sauce": ["tomato", "basil"],
  "directions": [
    {"step": 1, "description": "Boil water", "image": ""},
    {"step": 2, "description": "Cook pasta", "image": ""}
  ],
  "prep_time": "10 min",
  "cook_time": "20 min",
  "category": "Italian",
  "is_like": true,
  "writer": "Chef A"
}


### GET CATEGORIES BY ID
Get http://localhost:8080/api/recipe/3
Accept: application/json

### UPDATE CATEGORY BY ID
PUT    http://localhost:8080/api/recipe/4
Accept: application/json
Content-Type: application/json

{
    "title": "Spaghetti Bolognese IV",
  "description": "Delicious pasta",
  "image": "GambarIV.com",
  "nutrition": {
    "calories": "400 kcal",
    "total_fat": "12g",
    "protein": "20g",
    "carbohydrate": "50g",
    "cholesterol": "0mg",
    "description": "Low sugar"
  },
  "main_dish": ["pasta", "meat"],
  "sauce": ["tomato", "basil"],
  "directions": [
    {"step": 1, "description": "Boil water", "image": ""},
    {"step": 2, "description": "Cook pasta", "image": ""}
  ],
  "prep_time": "10 min",
  "cook_time": "20 min",
  "category": "Italian",
  "is_like": true,
  "writer": "Chef B"
}

### PATCH CATEGORY BY ID
PATCH     http://localhost:8080/api/recipe/3
Accept: application/json
Content-Type: application/json

{
  "title": "Spaghetti Bolognese 100",
  "nutrition": {
    "calories":"500 cal",
    "fat":"4000000 cal"
  }
}

### DELETE CATEGORY BY ID
DELETE   http://localhost:8080/api/recipe/1
Accept: application/json