### GET ALL CATEGORIES
Get http://localhost:3000/api/categories
Accept: application/json
X-API-Key:SECRET


### CREATE NEW CATEGORY
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
    "name" : ""
}

### GET CATEGORIES BY ID
Get http://localhost:3000/api/categories/2
Accept: application/json

### UPDATE CATEGORY BY ID
PUT  http://localhost:3000/api/categories/2
Accept: application/json
Content-Type: application/json

{
    "name" : "MAditP"
}

### DELETE CATEGORY BY ID
DELETE   http://localhost:3000/api/categories/2
Accept: application/json