// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"foodieland/controller"
	"foodieland/repository"
	"foodieland/service"
	"foodieland/validation"
)

// Injectors from wire.go:

func InitializeRecipeController(db *sql.DB) controller.RecipeController {
	recipeRepository := repository.NewRecipeRepositoryImpl()
	validate := validation.NewValidator()
	recipeService := service.NewRecipeServiceImpl(recipeRepository, db, validate)
	recipeController := controller.NewRecipeControllerImpl(recipeService)
	return recipeController
}
